# ---------------------------------------------------------------------------
# system: ModelArchivist
# file: config.toml
# purpose: Application configuration
# ---------------------------------------------------------------------------

[folder_paths]
comfy_root = "test/data/ComfyUI"
inactive_root = "test/data/inactive"
archive_root = "test/data/archive"
database = "test/model_archivist.db"
workflow_active = "test/data/workflow_active"
workflow_inactive = "test/data/workflow_inactive"
workflow_archive = "test/data/workflow_archive"

[settings]
restrict_to_known_types = false # ignored in current version

[[extra_models]]
yaml = "test/data/extra_model_paths.yaml"
inactive = "test/data/extra_inactive"
archive = "test/data/extra_archive"

[models]
extensions = [".safetensors", ".sft", ".ckpt", ".pt", ".pth", ".gguf"]

[model_types]
checkpoints = "Checkpoint"
clip = "CLIP"
clip_vision = "CLIP Vision"
controlnet = "Controlnet"
diffusers = "Diffuser"
diffusion_models = "Diffusion model"
embeddings = "Embedding"
gligen = "GLIGEN"
hypernetworks = "Hypernetwork"
latent_upscale_models = "Upscaler (latent)"
loras = "LoRA"
model_patches = "Model patch"
photomaker = "PhotoMaker"
style_models = "Style"
text_encoders = "Text encoder"
unet = "U-Net"
upscale_models = "Upscaler"
vae = "VAE"
vae_approx = "Tiny AutoEncoder"

[web]
# html_root = ...
url_base = "http://127.0.0.1"
port = 5173