# ---------------------------------------------------------------------------
# system: ModelArchivist
# file: config.toml
# purpose: Application config
# ---------------------------------------------------------------------------

[folders]
comfy_root = "test/data/ComfyUI"
archive_root = "test/data/archive"
database = "test/model_archivist.db"
workflow_root = "test/data/workflow_root"
workflow_archive = "test/data/workflow_archive"

[[extra_models]]
yaml = "test/data/extra_models_1.yaml"
archive = "test/data/extra_archive_1"

[models]
extensions = [".safetensors", ".sft", ".ckpt", ".pt", ".pth", ".gguf"]
ignore_types = ["examples", "configs"]

[model_types]
checkpoints = "Checkpoint"
clip = "CLIP"
clip_vision = "CLIP Vision"
controlnet = "Controlnet"
diffusers = "Diffuser"
diffusion_models = "Diffusion model"
embeddings = "Embedding"
gligen = "GLIGEN"
hypernetworks = "Hypernetwork"
latent_upscale_models = "Upscaler (latent)"
loras = "LoRA"
model_patches = "Model patch"
photomaker = "PhotoMaker"
style_models = "Style"
text_encoders = "Text encoder"
unet = "U-Net"
upscale_models = "Upscaler"
vae = "VAE"
vae_approx = "Tiny AutoEncoder"

[web]
url = "http://127.0.0.1:5173"

[options]
update_json_metadata = true     # update metadata when values change - has consequences for Lora
force_rehash = false    # re-calculate all the hashes when scanning the files
reset_force_rehash = true       # reset force_rehash to false after scan
ignore_unknown_types = false    # ignore models not in the model_types list
remove_inaccessible = true      # remove all models from inaccessible folders