# ---------------------------------------------------------------------------
# system: ModelArchivist
# file: config.toml
# purpose: Application configuration
# ---------------------------------------------------------------------------

[paths]
comfy_root = "test/data/ComfyUI"
inactive_root = "test/data/inactive"
archive_root = "test/data/archive"
database = "test/model_archivist.db"
workflow_active = "test/data/workflow_active"
workflow_inactive = "test/data/workflow_inactive"
workflow_archive = "test/data/workflow_archive"

[settings]
restrict_to_known_types = false # ignored in current version

[[extra_models]]
yaml = "test/data/extra_model_paths.yaml"
inactive = "test/data/extra_inactive"
archive = "test/data/extra_archive"

[models]
extensions = [".safetensors", ".sft", ".ckpt", ".pt", ".pth", ".gguf"]

[model_types]
loras = "LoRA"
checkpoints = "Checkpoint"
